### ISSUE TITLE
spwn: unable to open url

### ISSUE THREAD

**Issue by MassiveDegenerate** [pmrowla/streamlink-plugins#2]
When trying to use a SPWN VOD link I get the following error:
```
error: Unable to open URL: https://public.spwn.jp/event-pages/21112501-jpfantasy/streaming/data.json (404 Client Error: Not Found for url: https://public.spwn.jp/event-pages/21112501-jpfantasy/streaming/data.json)
```

**Comment by pmrowla** [comment]
What command did you run? The plugin expects the base event URL, not the link to the json data.

```
streamlink https://spwn.jp/events/21112501-jpfantasy best
```
works for me when I try that event 

(I have `--spwn-email` and `--spwn-password` configured in my streamlink config, but providing them as command options should also work)

**Comment by MassiveDegenerate** [comment]
Okay, I was using `streamlink https://virtual.spwn.jp/events/21112501-jpfantasy/streaming best` which was the issue, thanks for the correction.

**Comment by pmrowla** [comment]
Ah ok, so the plugin will work for `https://virtual.spwn.jp/events/21112501-jpfantasy/` as well, but it breaks when there is the extra `streaming` part in the URL.

I'll leave this open and fix it at some point, but in the mean time removing the `streaming` from the links will work
