### ISSUE TITLE
SPWN: Unable to fetch data.json on some events

### ISSUE THREAD

**Issue by ephemient** [pmrowla/streamlink-plugins#8]
https://spwn.jp/events/22052819-shigureui fails to retrieve `data.json` with a 404 error (same error in the browser), so the plugin doesn't work, but I can stream the event in the browser.

**Comment by pmrowla** [comment]
I don't have a ticket for the Ui event to test with. If you export a full network session for the event from chrome devtools I can take a look.

In chrome, open a tab + dev tools. In the `Network` tab make sure `Preserve log` is checked, and then open the event URL, then open the vod stream for playback. Once it has loaded the stream and starts playing the
 video you can stop the recording (red stop button all the way on the left). Then export the HAR file using the down arrow button.

![devtools](https://user-images.githubusercontent.com/651988/171076590-f5aede1d-f0e4-47ce-bf9e-337a09a72ecc.png)

Easiest way to send me the HAR is to just email it to peter@pmrowla.com. If you prefer uploading to something like gdrive or dropbox and posting/emailing a link that will work too.

**Comment by ephemient** [comment]
I sent the HAR by email as a gdrive link. Please let me know if there are any permissions issues; it was too large as a direct attachment.

Looking into it, as best as I can tell, it's getting metadata from `/getSellingGoods/` and video parts from `/getStreamingKey/`.

**Comment by pmrowla** [comment]
Ah ok, the email got marked as spam in gmail, but I found it now. The gdrive link works for me, I'll take a look into this soon.
